install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages("rgdal")
install.packages("raster")
install.packages("rgl")
devtools::install_github("tylermorganwall/terrainmeshr")
install.packages("remotes")
remotes::install_github("tylermorganwall/rayimage")
devtools::install_github("tylermorganwall/rayshader")
# seems if install from CRAN instead of github, based on https://github.com/tylermorganwall/rayshader/issues/110#issuecomment-627080365 ,  can leave off terrainmeshr and raymage?
#install.packages("rayshader") 
